[MONITOR]
# Write data to InfluxDB
writeDB = False
# Flag for output of the functions
debug = False
# Create a new txt file for output
newfile = True
# Sign of starting temperature (1. or -1.)
temp_sign = 1.
# Output directory for file
outdir = None
# Output name for file
outfile_name = None

[ARDUINO]
baudrate = 115200
port = /dev/ttyACM0
# Number of seconds before timeout
timeout = 10.           
